@startuml Composition
title Relation de composition

class GestionMainCarte {
  - List<Carte> paquet
  - List<Carte> main
}

class Carte {
  - valeur : int
  - couleur : String
  - symbole : String
}

GestionMainCarte "1" *-- "0..52" Carte : paquet
GestionMainCarte "1" *-- "0..5" Carte : main
left to right direction

@enduml
